"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isRaceSession = exports.Flags = void 0;
var Flags;
(function (Flags) {
    Flags[Flags["Checkered"] = 1] = "Checkered";
    Flags[Flags["White"] = 2] = "White";
    Flags[Flags["Green"] = 4] = "Green";
    Flags[Flags["Yellow"] = 8] = "Yellow";
    Flags[Flags["Red"] = 16] = "Red";
    Flags[Flags["Blue"] = 32] = "Blue";
    Flags[Flags["Debris"] = 64] = "Debris";
    Flags[Flags["Crossed"] = 128] = "Crossed";
    Flags[Flags["YellowWaving"] = 256] = "YellowWaving";
    Flags[Flags["OneLapToGreen"] = 512] = "OneLapToGreen";
    Flags[Flags["GreenHeld"] = 1024] = "GreenHeld";
    Flags[Flags["TenToGo"] = 2048] = "TenToGo";
    Flags[Flags["FiveToGo"] = 4096] = "FiveToGo";
    Flags[Flags["RandomWaving"] = 8192] = "RandomWaving";
    Flags[Flags["Caution"] = 16384] = "Caution";
    Flags[Flags["CautionWaving"] = 32768] = "CautionWaving";
    Flags[Flags["Black"] = 65536] = "Black";
    Flags[Flags["Disqualify"] = 131072] = "Disqualify";
    Flags[Flags["Servicible"] = 262144] = "Servicible";
    Flags[Flags["Furled"] = 524288] = "Furled";
    Flags[Flags["Repair"] = 1048576] = "Repair";
    Flags[Flags["StartHidden"] = 268435456] = "StartHidden";
    Flags[Flags["StartReady"] = 536870912] = "StartReady";
    Flags[Flags["StartSet"] = 1073741824] = "StartSet";
    Flags[Flags["StartGo"] = 2147483648] = "StartGo";
})(Flags = exports.Flags || (exports.Flags = {}));
const isRaceSession = (data) => {
    var _a, _b, _c;
    const sessionNumber = data.SessionNum || -1;
    const sessionName = ((_c = (_b = (_a = data.SessionInfo) === null || _a === void 0 ? void 0 : _a.Sessions) === null || _b === void 0 ? void 0 : _b[sessionNumber]) === null || _c === void 0 ? void 0 : _c.SessionName) || null;
    return sessionName === "RACE";
};
exports.isRaceSession = isRaceSession;
